package cmd

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"github.com/spf13/cobra"

	platformaws "github.com/ffreis/platform-bootstrap/internal/aws"
)

// fetchedConfig is the JSON structure written to the output file.
// It matches the Terraform variable types in platform-org's variables.tf.
type fetchedConfig struct {
	Org              string                       `json:"org"`
	AWSProfile       string                       `json:"aws_profile"`
	Accounts         map[string]map[string]string `json:"accounts"`
	BudgetAlertEmail string                       `json:"budget_alert_email,omitempty"`
}

// backendConfig holds the values written to backend.local.hcl.
type backendConfig struct {
	Bucket        string
	DynamoDBTable string
	Region        string
}

// backendHCLTemplate is the content written to backend.local.hcl.
// It intentionally omits `key` — that lives in envs/prod/backend.hcl so it
// can be committed safely. Pass both files to terraform init:
//
//	terraform init \
//	  -backend-config=backend.local.hcl \
//	  -backend-config=../envs/prod/backend.hcl
var backendHCLTemplate = template.Must(template.New("backend").Parse(
	`# Generated by platform-bootstrap fetch — do not commit (gitignored).
# Contains real infrastructure identifiers for the root Terraform state.
# The state key lives in envs/prod/backend.hcl and IS committed.
#
# Usage (from stack/):
#   terraform init \
#     -backend-config=backend.local.hcl \
#     -backend-config=../envs/prod/backend.hcl
bucket         = "{{.Bucket}}"
dynamodb_table = "{{.DynamoDBTable}}"
region         = "{{.Region}}"
`))

// writeFetchedConfig writes fetched.auto.tfvars.json to outputPath and,
// if backendOutputPath is non-empty, writes backend.local.hcl there too.
func writeFetchedConfig(outputPath, backendOutputPath string) error {
	ctx := rootCmd.Context()
	tableName := deps.cfg.RegistryTableName()

	records, err := platformaws.FetchConfig(ctx, deps.clients.DynamoDB, tableName, "account")
	if err != nil {
		return fmt.Errorf("fetching account config: %w", err)
	}

	accounts := make(map[string]map[string]string, len(records))
	for _, rec := range records {
		accounts[rec.ConfigName] = rec.Data
	}

	adminRecords, err := platformaws.FetchConfig(ctx, deps.clients.DynamoDB, tableName, "admin")
	if err != nil {
		return fmt.Errorf("fetching admin config: %w", err)
	}
	var budgetAlertEmail string
	for _, rec := range adminRecords {
		if rec.ConfigName == "alert_email" {
			budgetAlertEmail = rec.Data["email"]
			break
		}
	}

	out := fetchedConfig{
		Org:              deps.cfg.OrgName,
		AWSProfile:       deps.cfg.AWSProfile,
		Accounts:         accounts,
		BudgetAlertEmail: budgetAlertEmail,
	}

	data, err := json.MarshalIndent(out, "", "  ")
	if err != nil {
		return fmt.Errorf("marshalling output: %w", err)
	}
	data = append(data, '\n')

	if outputPath == "-" {
		if _, err := os.Stdout.Write(data); err != nil {
			return fmt.Errorf("writing to stdout: %w", err)
		}
	} else {
		if err := os.MkdirAll(filepath.Dir(outputPath), 0755); err != nil {
			return fmt.Errorf("creating output directory: %w", err)
		}
		if err := os.WriteFile(outputPath, data, 0600); err != nil {
			return fmt.Errorf("writing output to %s: %w", outputPath, err)
		}
		deps.logger.Info("wrote tfvars", "path", outputPath, "accounts", len(accounts))
	}

	if backendOutputPath != "" {
		bcfg := backendConfig{
			Bucket:        deps.cfg.StateBucketName(),
			DynamoDBTable: deps.cfg.LockTableName(),
			Region:        deps.cfg.Region,
		}
		if err := writeBackendHCL(backendOutputPath, bcfg); err != nil {
			return err
		}
	}

	return nil
}

var fetchCmd = &cobra.Command{
	Use:   "fetch",
	Short: "Fetch platform config from the registry and write Terraform config files",
	Long: `fetch reads configuration stored in the bootstrap registry DynamoDB table
and writes the files that Terraform needs to init and apply platform-org.

Output files:
  --output       fetched.auto.tfvars.json — auto-loaded by Terraform, gitignored
  --backend-out  backend.local.hcl       — S3 backend config for terraform init, gitignored

Both files are gitignored by design — always derived from the registry.

Example:
  platform-bootstrap fetch \
    --org ffreis \
    --profile bootstrap \
    --output    ../ffreis-platform-org/envs/prod/fetched.auto.tfvars.json \
    --backend-out ../ffreis-platform-org/stack/backend.local.hcl`,

	RunE: func(cmd *cobra.Command, _ []string) error {
		outputPath, _ := cmd.Flags().GetString("output")
		backendOutputPath, _ := cmd.Flags().GetString("backend-out")

		deps.logger.Info("fetching platform config",
			"table", deps.cfg.RegistryTableName(),
			"output", outputPath,
			"backend_out", backendOutputPath,
		)

		if err := writeFetchedConfig(outputPath, backendOutputPath); err != nil {
			return &ExitError{Code: exitAWSError, Err: err}
		}

		deps.logger.Info("fetch complete", "output", outputPath, "backend_out", backendOutputPath)
		return nil
	},
}

// writeBackendHCL renders backend.local.hcl to path.
func writeBackendHCL(path string, cfg backendConfig) error {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("creating backend output directory: %w", err)
	}
	f, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0600)
	if err != nil {
		return fmt.Errorf("creating backend.local.hcl at %s: %w", path, err)
	}
	defer f.Close()
	if err := backendHCLTemplate.Execute(f, cfg); err != nil {
		return fmt.Errorf("rendering backend.local.hcl: %w", err)
	}
	deps.logger.Info("wrote backend config", "path", path)
	return nil
}

func init() {
	fetchCmd.Flags().String("output", "-",
		`path to write fetched.auto.tfvars.json; use "-" for stdout`)
	fetchCmd.Flags().String("backend-out", "",
		`path to write backend.local.hcl (e.g. ../ffreis-platform-org/stack/backend.local.hcl); omit to skip`)
	rootCmd.AddCommand(fetchCmd)
}
