package cmd

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	platformaws "github.com/ffreis/platform-bootstrap/internal/aws"
)

const testAdminEmail = "admin@example.com"

func TestRenderBackendHCL(t *testing.T) {
	t.Parallel()

	got := renderBackendHCL(backendConfig{
		Bucket:        `state"bucket`,
		DynamoDBTable: `locks\table`,
		Region:        "us-east-1",
	})

	wantParts := []string{
		"# Generated by platform-bootstrap fetch - do not commit (gitignored).",
		`bucket         = "state\"bucket"`,
		`dynamodb_table = "locks\\table"`,
		`region         = "us-east-1"`,
	}
	for _, want := range wantParts {
		if !strings.Contains(got, want) {
			t.Fatalf("renderBackendHCL() missing %q in output:\n%s", want, got)
		}
	}
	if !strings.HasSuffix(got, "\n") {
		t.Fatalf("renderBackendHCL() output should end with newline, got %q", got)
	}
}

func TestWriteBackendHCL(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), "stack", "backend.local.hcl")
	cfg := backendConfig{
		Bucket:        "state-bucket",
		DynamoDBTable: "state-locks",
		Region:        "us-east-1",
	}

	if err := writeBackendHCL(path, cfg); err != nil {
		t.Fatalf("writeBackendHCL() unexpected error: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() unexpected error: %v", err)
	}
	if got := string(data); got != renderBackendHCL(cfg) {
		t.Fatalf("writeBackendHCL() wrote unexpected content:\n%s", got)
	}

	info, err := os.Stat(path)
	if err != nil {
		t.Fatalf("Stat() unexpected error: %v", err)
	}
	if perms := info.Mode().Perm(); perms != 0600 {
		t.Fatalf("file perms: want 0600, got %#o", perms)
	}
}

func TestAccountsFromRecords(t *testing.T) {
	t.Parallel()

	records := []platformaws.ConfigRecord{
		{ConfigName: "dev", Data: map[string]string{"email": "dev@example.com"}},
		{ConfigName: "prod", Data: map[string]string{"email": "prod@example.com"}},
	}

	got := accountsFromRecords(records)
	if len(got) != 2 {
		t.Fatalf("accountsFromRecords() len = %d, want 2", len(got))
	}
	if got["dev"]["email"] != "dev@example.com" || got["prod"]["email"] != "prod@example.com" {
		t.Fatalf("accountsFromRecords() unexpected result: %+v", got)
	}
}

func TestAdminAlertEmail(t *testing.T) {
	t.Parallel()

	records := []platformaws.ConfigRecord{
		{ConfigName: "ignored", Data: map[string]string{"email": "ignored@example.com"}},
		{ConfigName: "alert_email", Data: map[string]string{"email": testAdminEmail}},
	}
	if got := adminAlertEmail(records); got != testAdminEmail {
		t.Fatalf("adminAlertEmail() = %q, want %q", got, testAdminEmail)
	}
	if got := adminAlertEmail(nil); got != "" {
		t.Fatalf("adminAlertEmail(nil) = %q, want empty string", got)
	}
}

func TestWriteFetchedJSONFile(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), "envs", "prod", "fetched.auto.tfvars.json")
	data := []byte("{\"org\":\"acme\"}\n")

	if err := writeFetchedJSON(path, data, 1); err != nil {
		t.Fatalf("writeFetchedJSON() unexpected error: %v", err)
	}

	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() unexpected error: %v", err)
	}
	if string(got) != string(data) {
		t.Fatalf("writeFetchedJSON() wrote %q, want %q", string(got), string(data))
	}

	info, err := os.Stat(path)
	if err != nil {
		t.Fatalf("Stat() unexpected error: %v", err)
	}
	if perms := info.Mode().Perm(); perms != 0600 {
		t.Fatalf("file perms: want 0600, got %#o", perms)
	}
}
