package cmd

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRenderBackendHCL(t *testing.T) {
	t.Parallel()

	got := renderBackendHCL(backendConfig{
		Bucket:        `state"bucket`,
		DynamoDBTable: `locks\table`,
		Region:        "us-east-1",
	})

	wantParts := []string{
		"# Generated by platform-bootstrap fetch - do not commit (gitignored).",
		`bucket         = "state\"bucket"`,
		`dynamodb_table = "locks\\table"`,
		`region         = "us-east-1"`,
	}
	for _, want := range wantParts {
		if !strings.Contains(got, want) {
			t.Fatalf("renderBackendHCL() missing %q in output:\n%s", want, got)
		}
	}
	if !strings.HasSuffix(got, "\n") {
		t.Fatalf("renderBackendHCL() output should end with newline, got %q", got)
	}
}

func TestWriteBackendHCL(t *testing.T) {
	t.Parallel()

	oldLogger := deps.logger
	deps.logger = nil
	t.Cleanup(func() { deps.logger = oldLogger })

	path := filepath.Join(t.TempDir(), "stack", "backend.local.hcl")
	cfg := backendConfig{
		Bucket:        "state-bucket",
		DynamoDBTable: "state-locks",
		Region:        "us-east-1",
	}

	if err := writeBackendHCL(path, cfg); err != nil {
		t.Fatalf("writeBackendHCL() unexpected error: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() unexpected error: %v", err)
	}
	if got := string(data); got != renderBackendHCL(cfg) {
		t.Fatalf("writeBackendHCL() wrote unexpected content:\n%s", got)
	}

	info, err := os.Stat(path)
	if err != nil {
		t.Fatalf("Stat() unexpected error: %v", err)
	}
	if perms := info.Mode().Perm(); perms != 0600 {
		t.Fatalf("file perms: want 0600, got %#o", perms)
	}
}
