package cmd

import (
	"encoding/json"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	platformaws "github.com/ffreis/platform-bootstrap/internal/aws"
)

const testAdminEmail = "admin@example.com"

func TestRenderBackendHCL(t *testing.T) {
	t.Parallel()

	got := renderBackendHCL(backendConfig{
		Bucket:        `state"bucket`,
		DynamoDBTable: `locks\table`,
		Region:        "us-east-1",
	})

	wantParts := []string{
		"# Generated by platform-bootstrap fetch - do not commit (gitignored).",
		`bucket         = "state\"bucket"`,
		`dynamodb_table = "locks\\table"`,
		`region         = "us-east-1"`,
	}
	for _, want := range wantParts {
		if !strings.Contains(got, want) {
			t.Fatalf("renderBackendHCL() missing %q in output:\n%s", want, got)
		}
	}
	if !strings.HasSuffix(got, "\n") {
		t.Fatalf("renderBackendHCL() output should end with newline, got %q", got)
	}
}

func TestWriteBackendHCL(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), "stack", "backend.local.hcl")
	cfg := backendConfig{
		Bucket:        "state-bucket",
		DynamoDBTable: "state-locks",
		Region:        "us-east-1",
	}

	if err := writeBackendHCL(path, cfg); err != nil {
		t.Fatalf("writeBackendHCL() unexpected error: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() unexpected error: %v", err)
	}
	if got := string(data); got != renderBackendHCL(cfg) {
		t.Fatalf("writeBackendHCL() wrote unexpected content:\n%s", got)
	}

	info, err := os.Stat(path)
	if err != nil {
		t.Fatalf("Stat() unexpected error: %v", err)
	}
	if perms := info.Mode().Perm(); perms != 0600 {
		t.Fatalf("file perms: want 0600, got %#o", perms)
	}
}

func TestAccountsFromRecords(t *testing.T) {
	t.Parallel()

	records := []platformaws.ConfigRecord{
		{ConfigName: "dev", Data: map[string]string{"email": "dev@example.com"}},
		{ConfigName: "prod", Data: map[string]string{"email": "prod@example.com"}},
	}

	got := accountsFromRecords(records)
	if len(got) != 2 {
		t.Fatalf("accountsFromRecords() len = %d, want 2", len(got))
	}
	if got["dev"]["email"] != "dev@example.com" || got["prod"]["email"] != "prod@example.com" {
		t.Fatalf("accountsFromRecords() unexpected result: %+v", got)
	}
}

func TestAdminAlertEmails(t *testing.T) {
	t.Parallel()

	const second = "ops@example.com"

	tests := []struct {
		name    string
		records []platformaws.ConfigRecord
		want    []string
	}{
		{
			name: "single address is returned unchanged",
			records: []platformaws.ConfigRecord{
				{ConfigName: "ignored", Data: map[string]string{"email": "ignored@example.com"}},
				{ConfigName: "alert_email", Data: map[string]string{"email": testAdminEmail}},
			},
			want: []string{testAdminEmail},
		},
		{
			name: "comma separated addresses split in order",
			records: []platformaws.ConfigRecord{
				{ConfigName: "alert_email", Data: map[string]string{"email": testAdminEmail + "," + second}},
			},
			want: []string{testAdminEmail, second},
		},
		{
			name: "surrounding whitespace is trimmed",
			records: []platformaws.ConfigRecord{
				{ConfigName: "alert_email", Data: map[string]string{"email": "  " + testAdminEmail + " ,\t" + second + "\n"}},
			},
			want: []string{testAdminEmail, second},
		},
		{
			name: "trailing comma does not yield an empty entry",
			records: []platformaws.ConfigRecord{
				{ConfigName: "alert_email", Data: map[string]string{"email": testAdminEmail + "," + second + ","}},
			},
			want: []string{testAdminEmail, second},
		},
		{
			name: "interior blank entries are dropped",
			records: []platformaws.ConfigRecord{
				{ConfigName: "alert_email", Data: map[string]string{"email": testAdminEmail + ", ,," + second}},
			},
			want: []string{testAdminEmail, second},
		},
		{
			name: "empty string yields no recipients",
			records: []platformaws.ConfigRecord{
				{ConfigName: "alert_email", Data: map[string]string{"email": ""}},
			},
			want: nil,
		},
		{
			name: "commas only yields no recipients",
			records: []platformaws.ConfigRecord{
				{ConfigName: "alert_email", Data: map[string]string{"email": " , , "}},
			},
			want: nil,
		},
		{
			name: "missing email key yields no recipients",
			records: []platformaws.ConfigRecord{
				{ConfigName: "alert_email", Data: map[string]string{}},
			},
			want: nil,
		},
		{
			name:    "absent alert_email record yields no recipients",
			records: []platformaws.ConfigRecord{{ConfigName: "ignored", Data: map[string]string{"email": "ignored@example.com"}}},
			want:    nil,
		},
		{
			name:    "nil records yield no recipients",
			records: nil,
			want:    nil,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			got := adminAlertEmails(tt.records)
			if !slices.Equal(got, tt.want) {
				t.Fatalf("adminAlertEmails() = %#v, want %#v", got, tt.want)
			}
			if len(tt.want) == 0 && got != nil {
				t.Fatalf("adminAlertEmails() = %#v, want nil so omitempty drops the field", got)
			}
		})
	}
}

func TestPrimaryAlertEmail(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name   string
		emails []string
		want   string
	}{
		{name: "nil slice", emails: nil, want: ""},
		{name: "empty slice", emails: []string{}, want: ""},
		{name: "single entry", emails: []string{testAdminEmail}, want: testAdminEmail},
		{name: "first of many", emails: []string{testAdminEmail, "ops@example.com"}, want: testAdminEmail},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			if got := primaryAlertEmail(tt.emails); got != tt.want {
				t.Fatalf("primaryAlertEmail(%#v) = %q, want %q", tt.emails, got, tt.want)
			}
		})
	}
}

// TestFetchedConfigMarshalsBothEmailFields locks the wire contract consumers
// read: the plural list plus the deprecated singular first entry, and neither
// key emitted when no recipient is configured.
func TestFetchedConfigMarshalsBothEmailFields(t *testing.T) {
	t.Parallel()

	emails := adminAlertEmails([]platformaws.ConfigRecord{
		{ConfigName: "alert_email", Data: map[string]string{"email": testAdminEmail + ", ops@example.com"}},
	})
	data, err := json.Marshal(fetchedConfig{
		Org:               "acme",
		BudgetAlertEmail:  primaryAlertEmail(emails),
		BudgetAlertEmails: emails,
	})
	if err != nil {
		t.Fatalf("json.Marshal() unexpected error: %v", err)
	}

	got := string(data)
	for _, want := range []string{
		`"budget_alert_email":"` + testAdminEmail + `"`,
		`"budget_alert_emails":["` + testAdminEmail + `","ops@example.com"]`,
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("marshalled config missing %q in %s", want, got)
		}
	}

	empty, err := json.Marshal(fetchedConfig{Org: "acme"})
	if err != nil {
		t.Fatalf("json.Marshal() unexpected error: %v", err)
	}
	if strings.Contains(string(empty), "budget_alert_email") {
		t.Fatalf("empty config should omit both email keys, got %s", string(empty))
	}
}

func TestWriteFetchedJSONFile(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), "envs", "prod", "fetched.auto.tfvars.json")
	data := []byte("{\"org\":\"acme\"}\n")

	if err := writeFetchedJSON(path, data, 1); err != nil {
		t.Fatalf("writeFetchedJSON() unexpected error: %v", err)
	}

	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() unexpected error: %v", err)
	}
	if string(got) != string(data) {
		t.Fatalf("writeFetchedJSON() wrote %q, want %q", string(got), string(data))
	}

	info, err := os.Stat(path)
	if err != nil {
		t.Fatalf("Stat() unexpected error: %v", err)
	}
	if perms := info.Mode().Perm(); perms != 0600 {
		t.Fatalf("file perms: want 0600, got %#o", perms)
	}
}
