name: Semgrep Code Analysis

on:
  pull_request:
    paths:
      - '**'
      - '.github/workflows/**'
  push:
    paths:
      - '**'
      - '.github/workflows/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Install semgrep
        run: pip install "semgrep==1.99.0"

      - name: Run semgrep
        run: |
          set -euo pipefail
          semgrep scan --config "p/default" .
